import ObjectUtils from "../../utils/ObjectUtils";
import { DialogProps } from "../../types/Dialog";

export const DialogBase = {
  defaultProps: {
    __TYPE: "Dialog",
    appendTo: null,
    ariaCloseIconLabel: null,
    baseZIndex: 0,
    blockScroll: false,
    className: null,
    closable: true,
    closeOnEscape: true,
    contentClassName: null,
    contentStyle: null,
    dismissibleMask: false,
    draggable: true,
    focusOnShow: true,
    footer: null,
    header: null,
    headerClassName: null,
    headerStyle: null,
    icons: null,
    keepInViewport: true,
    maskClassName: null,
    maskStyle: null,
    maximizable: false,
    maximized: false,
    minimizable: false,
    minimized: false,
    minX: 0,
    minY: 0,
    hideMask: false,
    onClick: null,
    onDrag: null,
    onDragEnd: null,
    onDragStart: null,
    onHide: null,
    onMaskClick: null,
    onMaximize: null,
    onResize: null,
    onResizeEnd: null,
    onResizeStart: null,
    onShow: null,
    position: "center",
    resizable: true,
    rtl: false,
    showHeader: true,
    style: {},
    transitionOptions: null,
    visible: false,
    children: undefined,
    cancelButtonProps: {},
    okButtonProps: {},
    cancelButtonElement: null,
    okButtonElement: null,
  },
  getProps: (props: any): DialogProps => ObjectUtils.getMergedProps(props, DialogBase.defaultProps),
  getOtherProps: (props: any) => ObjectUtils.getDiffProps(props, DialogBase.defaultProps),
};
